version: '3.7'
services:
    deathrun:
        image: "ceifa/lory-gmod-deathrun"
        ports: 
            - "27015:27015"
            - "27015:27015/udp"
        volumes:
            - ./stateful/deathrun/data:/server/garrysmod/data
            - ./stateful/deathrun/sv.db:/server/garrysmod/sv.db
            - ./stateful/cache:/server/garrysmod/cache
        environment:
            - PRODUCTION=1
        restart: always
        tty: true
        build:
            context: .
            dockerfile: ./deathrun/Dockerfile
        networks:
            - lory

    murder:
        image: "ceifa/lory-gmod-murder"
        ports: 
            - "27016:27015"
            - "27016:27015/udp"
        volumes:
            - ./stateful/murder/data:/server/garrysmod/data
            - ./stateful/murder/sv.db:/server/garrysmod/sv.db
            - ./stateful/cache:/server/garrysmod/cache
        environment:
            - PRODUCTION=1
        restart: always
        tty: true
        build:
            context: .
            dockerfile: ./murder/Dockerfile
        networks:
            - lory

networks:
    lory: